name: Java CI/CD with Docker and GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/withus .

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/withus

  run-docker-image-on-ncp:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/withus:latest

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/deploy/"

      - name: Run blue-green.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            bash /home/ubuntu/deploy/blue-green.sh \
              "${{ secrets.DB_URL }}" \
              "${{ secrets.DB_USERNAME }}" \
              "${{ secrets.DB_PASSWORD }}" \
              "${{ secrets.JWT_SECRET }}" \
              "${{ secrets.MAIL_USERNAME }}" \
              "${{ secrets.MAIL_APP_PASSWORD }}" \
              "${{ secrets.COOLSMS_API_KEY }}" \
              "${{ secrets.COOLSMS_API_SECRET }}" \
              "${{ secrets.COOLSMS_SENDER_NUMBER }}" \
              "${{ secrets.DOCKERHUB_USERNAME }}" \
              "${{ secrets.BUCKET_NAME }}" \
              "${{ secrets.NCP_OS_ACCESS_KEY }}" \
              "${{ secrets.NCP_OS_SECRET_KEY }}" \
              "${{ secrets.MAIL_LOGO_URL }}" \
              "${{ secrets.MAIL_INTERVIEWER_AVAILABILITY_URL }}" \
              "${{ secrets.MAIL_EVALUATION_REMINDER_URL }}" \
              "${{ secrets.MAIL_INVITE_USER_URL }}" \
              "${{ secrets.DOCKERHUB_USERNAME }}/withus:latest"
